name: "Test Coverage" # To be able to access test coverage of the repository on SonarCloud
on:
  push:
    branches: [v6]
env:
  BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
  BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
  BROWSERSTACK_BUILD: "Test Coverage ${{ github.run_number }}"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Setup resources and environment
        uses: ./.github/actions/setup
        id: setup

      - name: Install Dependencies
        if: steps.setup.outputs.cache-dependencies-hit != 'true'
        run: npm ci --ignore-scripts --audit=false --fund=false

      - name: Reset NX # temporary
        run: npm run reset

      - name: Build
        if: steps.setup.outputs.cache-build-hit != 'true'
        run: npm run build

  sonarcloud:
    needs: build
    name: TestCoverage
    runs-on: ubuntu-latest
    steps:
      # - name: 'BrowserStack Env Setup' # Invokes the setup-env action
      #   uses: browserstack/github-actions/setup-env@master
      #   with:
      #     username: ${{ secrets.BROWSERSTACK_USERNAME }}
      #     access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

      # - name: 'BrowserStack Local Tunnel Setup' # Invokes the setup-local action
      #   uses: browserstack/github-actions/setup-local@master
      #   with:
      #     local-testing: start
      #     local-identifier: random

      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup resources and environment
        uses: ./.github/actions/setup
        id: setup

      - name: Test
        run: npm run test:all -- --parallel=3 --output minimal

      # - name: 'BrowserStackLocal Stop'  # Terminating the BrowserStackLocal tunnel connection
      #   uses: browserstack/github-actions/setup-local@master
      #   with:
      #     local-testing: stop

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
