name: Test
on: [push] # Triggers on any branch
env:
  # BASE_SHA: ${{ github.event.pull_request.base.sha }}
  BASE_SHA: 'ba97f656eb265eef6432baf7e4ecca1018bfc397'
  BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
  BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
  BROWSERSTACK_BUILD: "Test ${{ github.run_number }}"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          # Pulls all commits (needed for Lerna)
          fetch-depth: 0

      - name: Setup resources and environment
        uses: ./.github/actions/setup
        id: setup

      - name: Install Dependencies
        if: steps.setup.outputs.cache-dependencies-hit != 'true'
        run: npm ci --ignore-scripts --audit=false --fund=false

      - name: Reset NX # temporary
        run: npm run reset

      - name: Build
        if: steps.setup.outputs.cache-build-hit != 'true'
        run: npm run build:affected -- --base=$BASE_SHA

  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup resources and environment
        uses: ./.github/actions/setup

      - name: Lint
        run: npm run lint:affected -- --base=$BASE_SHA

  chrome:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Test
        uses: ./.github/actions/browserstack
        with:
          browsers: 'chrome'
          base: $BASE_SHA
          username: $BROWSERSTACK_USERNAME
          access-key: $BROWSERSTACK_ACCESS_KEY

  firefox:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Test
        uses: ./.github/actions/browserstack
        with:
          browsers: 'firefox'
          coverage: 'false'
          base: $BASE_SHA
          username: $BROWSERSTACK_USERNAME
          access-key: $BROWSERSTACK_ACCESS_KEY

  safari:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Test
        uses: ./.github/actions/browserstack
        with:
          browsers: 'safari'
          coverage: 'false'
          base: $BASE_SHA
          username: $BROWSERSTACK_USERNAME
          access-key: $BROWSERSTACK_ACCESS_KEY
