name: Nightly Test
on:
  schedule:
    - cron: '0 0 * * *'
env:
  BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
  BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
  BROWSERSTACK_BUILD: "Nightly Test ${{ github.run_number }}"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          # Pulls all commits (needed for Lerna)
          fetch-depth: 0

      - name: Setup resources and environment
        uses: ./.github/actions/setup
        id: setup

      - name: Install Dependencies
        if: steps.setup.outputs.cache-dependencies-hit != 'true'
        run: npm ci --ignore-scripts --audit=false --fund=false

      - name: Reset NX # temporary
        run: npm run reset

      - name: Build
        # Prevent NX caching it should always build
        run: npm run build -- --skip-nx-cache

  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup resources and environment
        uses: ./.github/actions/setup

      - name: Lint
        # Prevent NX caching because it must run all linting, even though the code has not chaged.
        run: npm run lint:all -- --skip-nx-cache

  nightly-test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      # - name: 'BrowserStack Env Setup' # Invokes the setup-env action
      #   uses: browserstack/github-actions/setup-env@master
      #   with:
      #     username: ${{ secrets.BROWSERSTACK_USERNAME }}
      #     access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

      # - name: 'BrowserStack Local Tunnel Setup' # Invokes the setup-local action
      #   uses: browserstack/github-actions/setup-local@master
      #   with:
      #     local-testing: start
      #     local-identifier: random

      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          # Pulls all commits (needed for Lerna)
          fetch-depth: 0

      - name: Setup resources and environment
        uses: ./.github/actions/setup
        id: setup

      - name: Test
        # Prevent NX caching because it must run all testing, even though the code has not chaged.
        run: npm run test:all -- --parallel=3 --skip-nx-cache --output minimal

      # - name: 'BrowserStackLocal Stop'  # Terminating the BrowserStackLocal tunnel connection
      #   uses: browserstack/github-actions/setup-local@master
      #   with:
      #     local-testing: stop
